[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 8888
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
